# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13stats_service.proto\x1a\x1bgoogle/protobuf/empty.proto\".\n\x07TopUser\x12\x0f\n\x07userIds\x18\x01 \x01(\t\x12\x12\n\nlikesCount\x18\x02 \x01(\x04\"#\n\x08TopUsers\x12\x17\n\x05users\x18\x01 \x03(\x0b\x32\x08.TopUser\"\x10\n\x02Id\x12\n\n\x02id\x18\x01 \x01(\t\":\n\x07TopPost\x12\x0e\n\x06postId\x18\x01 \x01(\t\x12\x10\n\x08\x61uthorId\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x04\" \n\x05Posts\x12\x17\n\x05posts\x18\x01 \x03(\x0b\x32\x08.TopPost\"\x17\n\x04Type\x12\x0f\n\x07isViews\x18\x01 \x01(\x08\"/\n\x05\x43ount\x12\x12\n\nlikesCount\x18\x01 \x01(\x04\x12\x12\n\nviewsCount\x18\x02 \x01(\x04\"/\n\x0cStatsRequest\x12\x13\n\x04type\x18\x01 \x01(\x0b\x32\x05.Type\x12\n\n\x02id\x18\x02 \x01(\t2}\n\x0cStatsService\x12\x19\n\x08GetStats\x12\x03.Id\x1a\x06.Count\"\x00\x12\x1e\n\x0bGetTopPosts\x12\x05.Type\x1a\x06.Posts\"\x00\x12\x32\n\x0bGetTopUsers\x12\x16.google.protobuf.Empty\x1a\t.TopUsers\"\x00\x42\x11Z\x0f./stats_serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./stats_service'
  _globals['_TOPUSER']._serialized_start=52
  _globals['_TOPUSER']._serialized_end=98
  _globals['_TOPUSERS']._serialized_start=100
  _globals['_TOPUSERS']._serialized_end=135
  _globals['_ID']._serialized_start=137
  _globals['_ID']._serialized_end=153
  _globals['_TOPPOST']._serialized_start=155
  _globals['_TOPPOST']._serialized_end=213
  _globals['_POSTS']._serialized_start=215
  _globals['_POSTS']._serialized_end=247
  _globals['_TYPE']._serialized_start=249
  _globals['_TYPE']._serialized_end=272
  _globals['_COUNT']._serialized_start=274
  _globals['_COUNT']._serialized_end=321
  _globals['_STATSREQUEST']._serialized_start=323
  _globals['_STATSREQUEST']._serialized_end=370
  _globals['_STATSSERVICE']._serialized_start=372
  _globals['_STATSSERVICE']._serialized_end=497
# @@protoc_insertion_point(module_scope)
