@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Диаграмма сущностей социальной сети

skinparam linetype polyline

System_Boundary(mainBoundary, "Main microservice") {
    entity User {
        *user_id : UUID4 <<generated>>
        --
        *user_name : varchar(256) ([a-zA-Z_])
        *user_password_hash : string hashed (SHA3-512)
        --
        updatable part
        --
        *first_name: varchar(256)
        *last_name: varchar(256)
        *user_birthday: date(YYYY-MM-DD)
        *user_email: varchar(256) /' see https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address '/
        *user_phone: varchar(64)
    }
}

System_Boundary(commentsPostsBoundary, "Comments and posts microservice") {
    entity Post {
        *post_id : UUID4 <<generated>>
        --
        *user_id : UUID4 <<FK>>
        --
        *post_title : varchar(512)
        *post_text : string
    }

    entity Comment {
        *comment_id : UUID4 <<generated>>
        --
        *user_id : UUID4 <<FK>>
        --
        *parent_type : literal(<<post>>|<<comment>>)
        *parent_id : UUID4 <<FK>>
        --
        *comment_text : string
    }
}

System_Boundary(statisticsBoundary, "Statistics microservice") {
    entity Like {
        *user_id : UUID4 <<FK>>
        *post_id : UUID4 <<FK>>
    }

    entity View {
        *user_id : UUID4 <<FK>>
        *post_id : UUID4 <<FK>>
    }
}

User ||--o{ Post : Makes
User ||--o{ Comment : Makes
User ||--o{ Like : Hits
User ||--o{ View : Makes

Comment }o--|| Post : Owns
View }o--|| Post : Owns
Like }o--|| Post : Owns
@enduml