openapi: 3.0.3
info:
  description: SocialNetwork API
  title: Swagger SocialNetwork - OpenAPI 3.0
  version: 1.0.0
paths:
  /user/register:
    post:
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentionals'
        description: Credentionals
        required: true
      responses:
        "200":
          description: Successful operation
        "400":
          description: Login is already in use
      summary: Register a new user
  /user/login:
    post:
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentionals'
        description: Credentionals
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: successful operation
          headers:
            X-Expires-After:
              description: date in UTC when token expires
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "400":
          description: Invalid username/password supplied
      summary: Logs user into the system
  /user/update_me:
    put:
      operationId: updateMe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: User
        required: true
      responses:
        "200":
          description: successful operation
        "401":
          description: unauthorized
      summary: Updates user info
components:
  schemas:
    Credentionals:
      example:
        user_password: 2df2ac2db274c92c486948a76c162ccd912d015105b14c1fc26ca8b25c37fc98
        user_name: Elon_Mask
      properties:
        user_name:
          example: Elon_Mask
          maxLength: 256
          minLength: 1
          pattern: "^[a-zA-Z_]$"
          type: string
        user_password:
          description: hashedPassword (SHA3-512)
          example: 2df2ac2db274c92c486948a76c162ccd912d015105b14c1fc26ca8b25c37fc98
          type: string
      type: object
      xml:
        name: credentionals
    UserId:
      properties:
        id:
          example: c984a2c3-0246-4a3d-a1d8-857ce02a31b8
          format: uuid4
          type: string
      type: object
    User:
      example:
        user_birthday: 2000-01-23
        user_email: john@email.com
        last_name: James
        user_phone: "+78005553535"
        first_name: John
      properties:
        first_name:
          example: John
          maxLength: 256
          minLength: 1
          type: string
        last_name:
          example: James
          maxLength: 256
          minLength: 1
          type: string
        user_birthday:
          format: date
          type: string
        user_email:
          example: john@email.com
          format: email
          type: string
        user_phone:
          example: "+78005553535"
          maxLength: 64
          minLength: 1
          type: string
      type: object
      xml:
        name: user
