services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./scripts/init_db:/docker-entrypoint-initdb.d
      - postgresdata:/var/lib/postgresql/data
    networks:
      - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:5050:8080
    networks:
      - postgres

  main_service:
    build: .
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      hmacSecret: ${hmacSecret}
      POST_SERVICE_HOST: ${POST_SERVICE_HOST}
      POST_SERVICE_PORT: ${POST_SERVICE_PORT}
    ports:
      - 127.0.0.1:8080:8081
    depends_on:
      - postgres
    networks:
      - postgres
      - grpc
      - social-network-microserviced_kafka

volumes:
  postgresdata:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
  grpc:
    driver: bridge
  social-network-microserviced_kafka:
    external: true

