version: '3'

services:
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
        networks:
          - mongo-db
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_USER}
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_PASSWORD}
            - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD}
        depends_on:
            - mongo
        ports:
          - "127.0.0.1:8081:8081"
        networks:
          - mongo-db
    post_service:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - MONGO_USER=${MONGO_USER}
        - MONGO_PASSWORD=${MONGO_PASSWORD}
        - MONGO_DATABASE=${MONGO_DATABASE}
        - MONGO_COLLECTION=${MONGO_COLLECTION}
        - MONGO_PORT=27017
        - MONGO_HOST=mongo
      depends_on:
        - mongo
      networks:
        - social-network-microserviced_grpc
        - mongo-db
networks:
  social-network-microserviced_grpc:
    external: true
  mongo-db:
    driver: bridge

